<?php
/**
 * AvailabilityTypeEnum
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\EbayInventoryClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * The version of the OpenAPI document: 1.18.5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\EbayInventoryClient\Model;
use \OpenAPI\EbayInventoryClient\ObjectSerializer;

/**
 * AvailabilityTypeEnum Class Doc Comment
 *
 * @category Class
 * @description This enumeration type is used to indicate whether an inventory item has quantity available for purchase at the merchant&#39;s store indicated in the &lt;strong&gt;pickupAtLocationAvailability.merchantLocationKey&lt;/strong&gt; field. This type is only applicable to inventory available for In-Store Pickup orders. | - **IN_STOCK**: This enumeration value indicates that the inventory item has quantity available for purchase at the merchant&#39;s store indicated in the &lt;strong&gt;pickupAtLocationAvailability.merchantLocationKey&lt;/strong&gt; field. The quantity available for purchase is shown in the &lt;strong&gt;pickupAtLocationAvailability.quantity&lt;/strong&gt; field. If the product is \&quot;In Stock\&quot;, the corresponding &lt;strong&gt;pickupAtLocationAvailability.Quantity&lt;/strong&gt; value should be an integer value greater than 0. - **OUT_OF_STOCK**: This enumeration value indicates that the inventory item is out of stock at the merchant&#39;s store indicated in the &lt;strong&gt;pickupAtLocationAvailability.merchantLocationKey&lt;/strong&gt; field. If the product is \&quot;Out of Stock\&quot;, the corresponding &lt;strong&gt;pickupAtLocationAvailability.Quantity&lt;/strong&gt; value should be 0. - **SHIP_TO_STORE**: This enumeration value indicates that the merchant&#39;s store (indicated in the &lt;strong&gt;pickupAtLocationAvailability.merchantLocationKey&lt;/strong&gt; field) is temporarily out of stock of the product, but some inventory of the product is being shipped from a warehouse to that store. The quantity being shipped is shown in the &lt;strong&gt;pickupAtLocationAvailability.quantity&lt;/strong&gt; field, and this value should be an integer value greater than 0.
 * @package  OpenAPI\EbayInventoryClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AvailabilityTypeEnum
{
    /**
     * Possible values of this enum
     */
    const IN_STOCK = 'IN_STOCK';
    const OUT_OF_STOCK = 'OUT_OF_STOCK';
    const SHIP_TO_STORE = 'SHIP_TO_STORE';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::IN_STOCK,
            self::OUT_OF_STOCK,
            self::SHIP_TO_STORE,
        ];
    }
}


