<?php
/**
 * FormatTypeEnum
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\EbayInventoryClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * The version of the OpenAPI document: 1.18.5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\EbayInventoryClient\Model;
use \OpenAPI\EbayInventoryClient\ObjectSerializer;

/**
 * FormatTypeEnum Class Doc Comment
 *
 * @category Class
 * @description This enumeration type is used to indicate the listing format of the offer.&lt;br&gt;&lt;br&gt;&lt;span class&#x3D;\&quot;tablenote\&quot;&gt;&lt;strong&gt;Note:&lt;/strong&gt; When creating an &lt;i&gt;auction&lt;/i&gt; offer, one of the available quantities for the inventory item are reserved for the auction offer. If the offer ends without a bid, the allocated quantity will be released and available for fixed-price offers.&lt;/span&gt; | - **AUCTION**: This enumeration value indicates that the listing format of the offer is auction. - **FIXED_PRICE**: This enumeration value indicates that the listing format of the offer is fixed-price.
 * @package  OpenAPI\EbayInventoryClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FormatTypeEnum
{
    /**
     * Possible values of this enum
     */
    const AUCTION = 'AUCTION';
    const FIXED_PRICE = 'FIXED_PRICE';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AUCTION,
            self::FIXED_PRICE,
        ];
    }
}


