<?php
/**
 * LengthUnitOfMeasureEnum
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\EbayInventoryClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * The version of the OpenAPI document: 1.18.5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\EbayInventoryClient\Model;
use \OpenAPI\EbayInventoryClient\ObjectSerializer;

/**
 * LengthUnitOfMeasureEnum Class Doc Comment
 *
 * @category Class
 * @description This enumeration type is used to specify/indicate the unit of measurement with which the dimensions of the shipping package are being measured. | - **INCH**: This enumeration value indicates that the dimensions of the shipping package is being measured in inches. - **FEET**: This enumeration value indicates that the dimensions of the shipping package is being measured in feet. - **CENTIMETER**: This enumeration value indicates that the dimensions of the shipping package is being measured in centimeters. - **METER**: This enumeration value indicates that the dimensions of the shipping package is being measured in meters.
 * @package  OpenAPI\EbayInventoryClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LengthUnitOfMeasureEnum
{
    /**
     * Possible values of this enum
     */
    const INCH = 'INCH';
    const FEET = 'FEET';
    const CENTIMETER = 'CENTIMETER';
    const METER = 'METER';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::INCH,
            self::FEET,
            self::CENTIMETER,
            self::METER,
        ];
    }
}


