<?php
/**
 * ListingStatusEnum
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\EbayInventoryClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * The version of the OpenAPI document: 1.18.5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\EbayInventoryClient\Model;
use \OpenAPI\EbayInventoryClient\ObjectSerializer;

/**
 * ListingStatusEnum Class Doc Comment
 *
 * @category Class
 * @description This enumeration type is used to indicate the status of the eBay listing that is associated with the corresponding offer. | - **ACTIVE**: This enumeration value indicates that the eBay listing associated with the offer is active. - **OUT_OF_STOCK**: This enumeration value indicates that the eBay listing associated with the offer is still active, but that the product is currently out-of-stock. If a single-variation listing is out-of-stock, that listing will be kept alive but hidden from search. If a variation inside a multiple-variation listing is out-of-stock, only that variation is hidden, but the listing remains active and discoverable. - **INACTIVE**: This enumeration value indicates that the eBay listing associated with the offer is currently inactive. - **ENDED**: This enumeration value indicates that the eBay listing associated with the offer has ended. - **EBAY_ENDED**: This enumeration value indicates that the eBay customer service has administratively ended the eBay listing associated with the offer. - **NOT_LISTED**: This enumeration value indicates that the eBay listing associated with the offer has yet to be listed.
 * @package  OpenAPI\EbayInventoryClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ListingStatusEnum
{
    /**
     * Possible values of this enum
     */
    const ACTIVE = 'ACTIVE';
    const OUT_OF_STOCK = 'OUT_OF_STOCK';
    const INACTIVE = 'INACTIVE';
    const ENDED = 'ENDED';
    const EBAY_ENDED = 'EBAY_ENDED';
    const NOT_LISTED = 'NOT_LISTED';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ACTIVE,
            self::OUT_OF_STOCK,
            self::INACTIVE,
            self::ENDED,
            self::EBAY_ENDED,
            self::NOT_LISTED,
        ];
    }
}


