<?php
/**
 * ShippingServiceTypeEnum
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\EbayInventoryClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * The version of the OpenAPI document: 1.18.5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\EbayInventoryClient\Model;
use \OpenAPI\EbayInventoryClient\ObjectSerializer;

/**
 * ShippingServiceTypeEnum Class Doc Comment
 *
 * @category Class
 * @description This enumeration type is used to specify/indicate whether the shipping service option whose shipping costs will be overridden is a domestic or an international shipping service. | - **DOMESTIC**: This enumeration value indicates that the shipping service option whose shipping costs will be overridden is a domestic shipping service. - **INTERNATIONAL**: This enumeration value indicates that the shipping service option whose shipping costs will be overridden is an international shipping service.
 * @package  OpenAPI\EbayInventoryClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ShippingServiceTypeEnum
{
    /**
     * Possible values of this enum
     */
    const DOMESTIC = 'DOMESTIC';
    const INTERNATIONAL = 'INTERNATIONAL';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DOMESTIC,
            self::INTERNATIONAL,
        ];
    }
}


