<?php
/**
 * SoldOnEnum
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\EbayInventoryClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * The version of the OpenAPI document: 1.18.5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\EbayInventoryClient\Model;
use \OpenAPI\EbayInventoryClient\ObjectSerializer;

/**
 * SoldOnEnum Class Doc Comment
 *
 * @category Class
 * @description This enumeration type is used to indicate if the product was sold for the price in the &lt;strong&gt;originalRetailPrice&lt;/strong&gt; field on an eBay site, or sold for that price by a third-party retailer. This type is only applicable if the seller and listing are eligible to use the Strikethrough Pricing feature, a feature which is limited to the US (core site and Motors), UK, Germany, Canada (English and French versions), France, Italy, and Spain. | - **ON_EBAY**: This enumeration value indicates that the product was sold for the price in the &lt;strong&gt;originalRetailPrice&lt;/strong&gt; field on an eBay site. - **OFF_EBAY**: This enumeration value indicates that the product was sold for the &lt;strong&gt;originalRetailPrice&lt;/strong&gt; through a third-party retailer. - **ON_AND_OFF_EBAY**: This enumeration value indicates that the product was sold for the &lt;strong&gt;originalRetailPrice&lt;/strong&gt; on an eBay site and through a third-party retailer.
 * @package  OpenAPI\EbayInventoryClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SoldOnEnum
{
    /**
     * Possible values of this enum
     */
    const ON_EBAY = 'ON_EBAY';
    const OFF_EBAY = 'OFF_EBAY';
    const ON_AND_OFF_EBAY = 'ON_AND_OFF_EBAY';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ON_EBAY,
            self::OFF_EBAY,
            self::ON_AND_OFF_EBAY,
        ];
    }
}


