<?php
/**
 * TimeDurationUnitEnum
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\EbayInventoryClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * The version of the OpenAPI document: 1.18.5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\EbayInventoryClient\Model;
use \OpenAPI\EbayInventoryClient\ObjectSerializer;

/**
 * TimeDurationUnitEnum Class Doc Comment
 *
 * @category Class
 * @description This enumeration type is used by the &lt;strong&gt;fulfillmentTime&lt;/strong&gt; field of the &lt;strong&gt;PickupAtLocationAvailability&lt;/strong&gt; type to specify the time unit that is used to indicate the fulfillment time, which is how soon an In-Store Pickup order will be ready for pickup at the store identified in the corresponding &lt;strong&gt;merchantLocationKey&lt;/strong&gt; field. Typically, the unit value will be &lt;code&gt;HOUR&lt;/code&gt;. | - **YEAR**: Time duration is based on a number of years. - **MONTH**: Time duration is based on a number of months - **DAY**: Time duration is based on a number of days. - **HOUR**: Time duration is based on a number of hours. - **CALENDAR_DAY**: Time duration is based on a number of calendar days, including Saturday and Sunday. This time duration does not exclude holidays. - **BUSINESS_DAY**: Time duration is based on a number of business days, or &#39;working days&#39; (normally Monday through Friday). This excludes Sunday and all holidays in the time duration and, depending on the location, can include or exclude Saturday. - **MINUTE**: Time duration is based on a number of minutes. - **SECOND**: Time duration is based on a number of seconds. - **MILLISECOND**: Time duration is based on a number of milliseconds.
 * @package  OpenAPI\EbayInventoryClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TimeDurationUnitEnum
{
    /**
     * Possible values of this enum
     */
    const YEAR = 'YEAR';
    const MONTH = 'MONTH';
    const DAY = 'DAY';
    const HOUR = 'HOUR';
    const CALENDAR_DAY = 'CALENDAR_DAY';
    const BUSINESS_DAY = 'BUSINESS_DAY';
    const MINUTE = 'MINUTE';
    const SECOND = 'SECOND';
    const MILLISECOND = 'MILLISECOND';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::YEAR,
            self::MONTH,
            self::DAY,
            self::HOUR,
            self::CALENDAR_DAY,
            self::BUSINESS_DAY,
            self::MINUTE,
            self::SECOND,
            self::MILLISECOND,
        ];
    }
}


