<?php
/**
 * ProductSafetyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\EbayInventoryClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * The version of the OpenAPI document: 1.18.5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\EbayInventoryClient;

use PHPUnit\Framework\TestCase;

/**
 * ProductSafetyTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used to define the &lt;b&gt;pictograms&lt;/b&gt; and &lt;b&gt;statement&lt;/b&gt; containers, and the optional &lt;b&gt;component&lt;/b&gt; field, that provide product safety and compliance related information.
 * @package     OpenAPI\EbayInventoryClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProductSafetyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductSafety"
     */
    public function testProductSafety()
    {
    }

    /**
     * Test attribute "component"
     */
    public function testPropertyComponent()
    {
    }

    /**
     * Test attribute "pictograms"
     */
    public function testPropertyPictograms()
    {
    }

    /**
     * Test attribute "statements"
     */
    public function testPropertyStatements()
    {
    }
}
