<?php
/**
 * RegulatoryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\EbayInventoryClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * The version of the OpenAPI document: 1.18.5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\EbayInventoryClient;

use PHPUnit\Framework\TestCase;

/**
 * RegulatoryTest Class Doc Comment
 *
 * @category    Class
 * @description Type defining regulatory information that the seller is required to disclose.
 * @package     OpenAPI\EbayInventoryClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RegulatoryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Regulatory"
     */
    public function testRegulatory()
    {
    }

    /**
     * Test attribute "documents"
     */
    public function testPropertyDocuments()
    {
    }

    /**
     * Test attribute "energy_efficiency_label"
     */
    public function testPropertyEnergyEfficiencyLabel()
    {
    }

    /**
     * Test attribute "hazmat"
     */
    public function testPropertyHazmat()
    {
    }

    /**
     * Test attribute "manufacturer"
     */
    public function testPropertyManufacturer()
    {
    }

    /**
     * Test attribute "product_safety"
     */
    public function testPropertyProductSafety()
    {
    }

    /**
     * Test attribute "repair_score"
     */
    public function testPropertyRepairScore()
    {
    }

    /**
     * Test attribute "responsible_persons"
     */
    public function testPropertyResponsiblePersons()
    {
    }
}
