<?php
/**
 * SameDayShippingCutOffTimesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\EbayInventoryClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * The version of the OpenAPI document: 1.18.5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\EbayInventoryClient;

use PHPUnit\Framework\TestCase;

/**
 * SameDayShippingCutOffTimesTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used by the &lt;b&gt;createInventoryLocation&lt;/b&gt; call to specify cut-off time(s) for an inventory location, as well as any overrides for these times.
 * @package     OpenAPI\EbayInventoryClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SameDayShippingCutOffTimesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SameDayShippingCutOffTimes"
     */
    public function testSameDayShippingCutOffTimes()
    {
    }

    /**
     * Test attribute "overrides"
     */
    public function testPropertyOverrides()
    {
    }

    /**
     * Test attribute "weekly_schedule"
     */
    public function testPropertyWeeklySchedule()
    {
    }
}
