<?php
/**
 * WeightUnitOfMeasureEnumTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\EbayInventoryClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * The version of the OpenAPI document: 1.18.5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\EbayInventoryClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * WeightUnitOfMeasureEnumTest Class Doc Comment
 *
 * @category    Class
 * @description This enumerated type is used to indicate what unit of measurement is used to measure the weight of a shipping package. The weight and dimensions of a shipping package are generally required when calculated shipping rates are used, and weight is required if flat-rate shipping is used, but the seller is charging a weight surcharge. | - **POUND**: This enumeration value indicates that the unit of measurement used for measuring the weight of the shipping package is pounds. - **KILOGRAM**: This enumeration value indicates that the unit of measurement used for measuring the weight of the shipping package is kilograms. - **OUNCE**: This enumeration value indicates that the unit of measurement used for measuring the weight of the shipping package is ounces. - **GRAM**: This enumeration value indicates that the unit of measurement used for measuring the weight of the shipping package is grams.
 * @package     OpenAPI\EbayInventoryClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class WeightUnitOfMeasureEnumTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "WeightUnitOfMeasureEnum"
     */
    public function testWeightUnitOfMeasureEnum()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
